<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="RJINDAL" name="com.seleniumtests.cucumbertest.java.RunCucumberTests" tests="1" failures="1" timestamp="17 Nov 2014 11:43:07 GMT" time="117.740" errors="0">
  <testcase name="runCukes" time="117.740" classname="com.seleniumtests.cucumbertest.java.RunCucumberTests">
    <failure type="cucumber.runtime.CucumberException" message="java.lang.AssertionError: java.lang.AssertionError: expected [false] but found [true]java.lang.AssertionError: expected [true] but found [false]">
      <![CDATA[cucumber.runtime.CucumberException: java.lang.AssertionError: java.lang.AssertionError: expected [false] but found [true]java.lang.AssertionError: expected [true] but found [false]
	at cucumber.api.testng.TestNGCucumberRunner.runCukes(TestNGCucumberRunner.java:58)
	at com.seleniumtests.cucumbertest.java.RunCucumberTests.runCukes(RunCucumberTests.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: java.lang.AssertionError: expected [false] but found [true]java.lang.AssertionError: expected [true] but found [false]
	at com.thoughtworks.selenium.SeleneseTestBase.fail(SeleneseTestBase.java:391)
	at com.seleniumtests.core.CustomVerification.checkForVerificationErrors(CustomVerification.java:102)
	at com.seleniumtests.cucumbertest.java.ClubRegSteps.i_get_welcome_page(ClubRegSteps.java:113)
	at âœ½.And i get welcome page(src/test/resources/com/seleniumtests/cucumbertest/features/ClubRegNew.feature:16)
]]>
    </failure>
  </testcase> <!-- runCukes -->
</testsuite> <!-- com.seleniumtests.cucumbertest.java.RunCucumberTests -->
